# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and release for Win & Mac
on:
  push:
    branches: [ main ]

jobs:
  build-release:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2    
      - name: Use Node.js ${{ matrix.node-version }}   
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build

    - name: Github Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_SECRET }}
      with:
        name: Release V${{ github.run_number }}
        files: "dist/Scratch Arduino Link 0.1.0*.*"