# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and release for Win & Mac
on:
  push:
    branches: [ main ]
    tag:
      - 'v*.*.*'

jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2    
      - name: Use Node.js ${{ matrix.node-version }}   
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build

      - name: Cleanup Windows artifacts
        if: matrix.os == 'windows-latest'
        run: npx rimraf "dist/!(*.exe)"

      - name: Cleanup Mac OS artifacts
        if: matrix.os == 'windows-latest'
        run: npx rimraf "dist/!(*.dmg)"

      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $RELEASE_VERSION

      - name: Github Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_SECRET v${{ RELEASE_VERSION }}*.* }}
        with:
          files: "dist/scratch-arduino-link *"
          name: Release V${{ RELEASE_VERSION }}
          tag_name: v${{ RELEASE_VERSION }}